### ISSUE TITLE
Question regarding why logout() implements globalLogout

### ISSUE THREAD

**Issue by guilsa** [frsechet/cognito-user-pool#3]
Does logout for a specific device work? I've noticed logout() from Cognito's official SDK assumes cognitoUser class instance persists between login/logout session. That's a strange. I imagine it'd only work if you give it global scope. Is this why you're implementing globalLogout instead?

**Comment by frsechet** [comment]
Hello,
no. There is no notion of device with this package as this is handled by the standard AWS front-side cognito SDK (JS, Java, Swift...) but of course the server doesn't know what device you're on unless you tell it specifically. I didn't have that need so I didn't spend the time looking into it.
