### ISSUE TITLE
Requiring in different modules

### ISSUE THREAD

**Issue by shnplr** [frsechet/cognito-user-pool#6]
Hi,
I'm using express and to use this in different modules do I need to pass the user pool data object around?  Is there some way I can require the wrapper once, say in app.js and then 'require' it another module without having to invoke the constructor again?

Thanks,
Paul

**Comment by frsechet** [comment]
Hi,

You are either looking for a middleware that will "augment" your request object with everything you need, or you might do something like this which is more "lightweight" (and probably what you should do in your situation - note that this applies to this module but also to anything you want to use in multiple places):

in cognitoWrapper.js
```
const poolData = {
  UserPoolId : USER_POOL_ID, // your user pool ID
  ClientId : USER_POOL_CLIENT_ID, // generated in the AWS console
  Paranoia : PARANOIA_LEVEL // an integer between 1 - 10
};
module.exports = require('cognito-user-pool')(poolData);
```

in any file you want to use the wrapper:
```
const cognitoWrapper = require('./cognitoWrapper');
...
cognitoWrapper.signup(...);
```

**Comment by shnplr** [comment]
Hi,
thanks for this - yes I just about realized that I would need to pull my 'config' load into a separate module, augmented with your idea to wrap the wrapper should work great.  Thanks so much I'll give that a go!
Cheers,
Paul
