### ISSUE TITLE
Sign in Error Username and Pool information required

### ISSUE THREAD

**Issue by khanxc** [frsechet/cognito-user-pool#7]
First of all thanks for this library, saves a ton of time. I am currently stuck in this error 

> Error: Username and pool information are required.

And this is my code 

```js 
app.post('/user/signin',(req,res) => {
		var   params =  {
     		"username": req.body.phone_number,
   			 "password": req.body.password
  						};
  CognitoUserPoolWrapper.login(params, (err,result) => {
  if(err) {
      res.status(404).send({
                 'status':'error',
                 'message':'Error authenticating user'
               });
               return
    }
	res.status(200).send(result);
  });
});

```

Where exactly do I have to add the username and pool info? And my pool data looks like this 
```js
const poolData = {
  UserPoolId : 'us-east-1_XXXXXXXX', // your user pool ID
  ClientId : '44XXXCCCAASSDLDLDLDLDL', // generated in the AWS console
  Paranoia : 0 // an integer between 1 - 10
};

let CognitoUserPoolWrapper = require('cognito-user-pool')(poolData);
```

**Comment by frsechet** [comment]
Hi,

it looks mostly alright, but a few things to look for:

- check that of course params.username is not empty, nor poolData,
- set poolDataParanoia to something between 1-10 (so not 0),
- in cognito console, check that your app client doesn't use the "generate client secret" option (recreate one if needed) 
<img width="263" alt="capture d ecran 2018-03-02 a 11 57 06" src="https://user-images.githubusercontent.com/7351940/36895916-f2b9d9de-1e10-11e8-92ba-3e6d36cd830e.png">
- in cognito console, check that the required parameters (email, phone_number etc.)match what you actually send

**Comment by khanxc** [comment]
Thanks for the guidance, the culprit was this line 
```js  
"username": req.body.phone_number 
```
Where in post body I was passing it as "username" 

```js
{
	"username":"+1778XXXXXXX",
	"password":"samplepass123#"
}
```
I changed it to **req.body.username** and everything worked perfectly. Thanks, my bad, I am closing it.
